name: "winapps"
volumes:
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: WinApps
    environment:
      VERSION: "${WIN_VERSION}"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "48G"
      USERNAME: "${WIN_USERNAME}"
      PASSWORD: "${WIN_PASSWORD}"
      HOME: "${HOME}"
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    cap_add:
      - NET_ADMIN
    stop_grace_period: 120s
    restart: on-failure
    volumes:
      - data:/storage
      - ${HOME}:/shared
      - ${OEM_PATH}:/oem
      - ${CUSTOM_ISO_PATH}:/custom.iso
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/kfd
      - /dev/dri
